name: echo action

on:
    pull_request:
      branches:
      - dev
      - main

defaults:
  run:
    shell: bash

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: echo
        run: echo "Hello, World!"
